package com.redhat.empowered.businessservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630224
 * 2017-02-24T10:23:08.403+01:00
 * Generated source version: 3.1.5.redhat-630224
 * 
 */
@WebService(targetNamespace = "http://www.redhat.com/empowered/businessService", name = "personPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonPortType {

    @WebMethod
    @WebResult(name = "person", targetNamespace = "http://www.redhat.com/empowered/businessService", partName = "parameters")
    public Person getPersonOp(
        @WebParam(partName = "parameters", name = "queryPerson", targetNamespace = "http://www.redhat.com/empowered/businessService")
        QueryPerson parameters
    );
}
